site_name: Reloaded II Documentation
site_url: https://reloaded-project.github.io/Reloaded-II/

repo_name: Reloaded-Project/Reloaded-II
repo_url: https://github.com/Reloaded-Project/Reloaded-II

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Sewer56
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheSewer56

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist
  - def_list
  - meta
  - md_in_html
  - attr_list
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  palette:
    scheme: reloaded-slate
  features:
    - navigation.instant

extra_css:
  - Custom/Stylesheets/extra.css

plugins:
  - search
  - redirects:
      redirect_maps:
        'Automation.md': 'ModTemplate.md'
        'BuildingMods.md': 'DevelopmentEnvironmentSetup.md'
        'PublishingMods.md': 'EnablingUpdateSupport.md'
        'InterModCommunication.md': 'DependencyInjection_HowItWork.md'
        'DependencyInjection.md': 'DependencyInjection_HowItWork.md'
  - exclude-unused-files:
      file_types_to_check: [ "psd", "7z", "kra" ]
      file_types_override_mode: append
      enabled: true
  - exclude:
      # Exclude the Theme's own files.
      glob:
        - Reloaded/Pages/*
        - Reloaded/docs/*
        - Reloaded/Readme.md
        - Reloaded/LICENSE
        - Reloaded/mkdocs.yml

theme:
  name: material
  palette:
    primary: red
    accent: red
    scheme: slate
  features:
    - navigation.instant
    
nav:
  - Home: index.md
  - For Users:
    - Quick Start: QuickStart.md
    - Frequently Asked Questions: FAQ.md
    - Linux Guides:
      - Linux Setup Guide: LinuxSetupGuideNew.md
      - Linux Setup Guide (Extra): LinuxSetupGuideNewExtra.md
      - Linux Setup Guide (Legacy): LinuxSetupGuide.md
    - Installing Mod Packs: InstallingModPacks.md
    - Advanced:
      - NuGet Sources: NuGetSources.md
      - Injection Methods: InjectionMethods.md
      - Misc & Experimental Features: ExperimentalFeatures.md
  - For Modders:
    - Getting Started: 
      - 1. Creating Your Mod: CreatingMods.md
      - 2. Adding Functionality: AddingModFunctionality.md
    - Releasing Mods:
      - 1. Enabling Update Support: EnablingUpdateSupport.md
      - 2. Creating a Release: CreatingRelease.md
      - Extras (Optional): CreatingReleaseExtras.md
    - Creating Mod Packs: CreatingModPacks.md

  - For Programmers:
    - Getting Started: 
        - 1. Setting Up Development Environment: DevelopmentEnvironmentSetup.md
        - 2. Creating a New Project: ProjectSetup.md
    - Cheat Sheet: 
      - 1. Memory Manipulation: CheatSheet/MemoryManipulation.md
      - 2. Calling & Hooking Game Functions: CheatSheet/CallingHookingGameFunctions.md
      - 3. Signature Scanning: CheatSheet/SignatureScanning.md
      - 4. Reloaded API: CheatSheet/ReloadedIIApi.md
    - Dependency Injection: 
      - 1. How Does it Work?: DependencyInjection_HowItWork.md
      - 2. How to Consume Dependencies: DependencyInjection_Consumer.md
      - 3. How to Publish Dependencies: DependencyInjection_Publisher.md
      - Extra:
        - Extra Features: DependencyInjection_ExtraFeatures.md
        - How does it Really Work: DependencyInjection_HowItReallyWork.md
    - Mod Template Features: ModTemplate.md
    - Writing Native Mods: NativeMods.md
    - Internal Libraries: 
      - Introduction: InternalLibrariesIntro.md
      - I/O Library: InternalLibrariesIO.md
      - Community Index: InternalLibrariesCommunity.md
      - Packaging: InternalLibrariesPackaging.md
      - Update: InternalLibrariesUpdate.md
      - Server: InternalLibrariesServer.md
    - Miscellaneous:
      - Adding Mod Update Support: AddingUpdateSupport.md
      - API Overview: APIOverview.md
      - Optimizing Mods: OptimizingMods.md
      - Shared Libraries: https://github.com/Sewer56/Reloaded.SharedLib.Hooks
      - Writing Mods for Actively Developed Games/Apps: https://github.com/Sewer56/Reloaded.SharedLib.Hooks#supporting-actively-developed-applications
      - Troubleshooting: Troubleshooting.md
  - For Contributors:
    - Building Reloaded: BuildingReloaded.md
    - Project Structure: ProjectStructure.md
    - High Level Architecture: Reloaded-II-Architecture.md
    - Translating Reloaded: LocalizingReloaded.md
    - Miscellaneous:
      - Reloaded vs Reloaded II: Reloaded-vs-Reloaded-II.md
  - Wiki: 
    - Contributing Locally: ContributingLocally.md
    - Contributing Online: ContributingOnline.md